# -*- coding: utf-8 -*-
"""dag_mission18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVC-EmmjPoE4uC_LrHYQaUJyDQTQ62NE
"""

from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.utils.dates import days_ago

import requests
import pandas as pd
from google.cloud import bigquery
from bs4 import BeautifulSoup
from google.cloud.bigquery import LoadJobConfig

# 기본 설정
API_KEY = '5Jr9kAcEEIKkksyjpJdQRu+e0xrNOSF9Z1abFVtBoF8fWMx0FQcZOgK2FGIFiDqczAqI06aNNQd8dQ6FD86DwQ==' #API 키 입력
SERVICE_URL = 'http://apis.data.go.kr/B552584/ArpltnInforInqireSvc/getCtprvnRltmMesureDnsty'
PROJECT_ID = 'codeit-airflow'           # BigQuery Project ID 
DATASET_ID = 'air_quality_dataset'          # BigQuery Dataset ID 
TABLE_ID = 'air_pollution'


# convert_string 함수: XML 태그의 값을 반환하는 함수
def convert_string(item, tag):
    value = item.find(tag)
    return value.get_text() if value else None

# parse_to_dataframe 함수: XML 데이터를 pandas DataFrame으로 변환
def parse_to_dataframe(xml_data):
    # XML을 파싱하기 위해 BeautifulSoup 사용

    xml = BeautifulSoup(xml_data.replace('\n', ''), "lxml")
    items = xml.findAll("item")
    print(f"가져온 항목 수: {len(items)}")

    item_list = []

    # 항목들 반복해서 딕셔너리로 추출
    for item in items:
        item_dict = {
            'station_name': convert_string(item, "stationname"),
            'network_info': convert_string(item, "mangname"),
            'province_name': convert_string(item, "sidoname"),
            'measurement_time': convert_string(item, "datatime"),
            'so2_concentration': convert_string(item, "so2value"),
            'co_concentration': convert_string(item, "covalue"),
            'o3_concentration': convert_string(item, "o3value"),
            'no2_concentration': convert_string(item, "no2value"),
            'pm10_concentration': convert_string(item, "pm10value"),
            'pm10_24h_prediction': convert_string(item, "pm10value24"),
            'pm25_concentration': convert_string(item, "pm25value"),
            'pm25_24h_prediction': convert_string(item, "pm25value24"),
            'air_quality_index': convert_string(item, "khaivalue"),
            'air_quality_grade': convert_string(item, "khaigrade"),
            'so2_grade': convert_string(item, "so2grade"),
            'co_grade': convert_string(item, "cograde"),
            'o3_grade': convert_string(item, "o3grade"),
            'no2_grade': convert_string(item, "no2grade"),
            'pm10_24h_grade': convert_string(item, "pm10grade"),
            'pm25_24h_grade': convert_string(item, "pm25grade"),
            'pm10_1h_grade': convert_string(item, "pm10grade1h"),
            'pm25_1h_grade': convert_string(item, "pm25grade1h"),
            'so2_flag': convert_string(item, "so2flag"),
            'co_flag': convert_string(item, "coflag"),
            'o3_flag': convert_string(item, "o3flag"),
            'no2_flag': convert_string(item, "no2flag"),
            'pm10_flag': convert_string(item, "pm10flag"),
            'pm25_flag': convert_string(item, "pm25flag"),
        }
        item_list.append(item_dict)

    df = pd.DataFrame(item_list)

    # Print 데이터
    print(df.head())

    return df


def fetch_and_load_to_bq(**context):
    # API 호출
    params = {
        'serviceKey': '5Jr9kAcEEIKkksyjpJdQRu+e0xrNOSF9Z1abFVtBoF8fWMx0FQcZOgK2FGIFiDqczAqI06aNNQd8dQ6FD86DwQ==',
        'returnType': 'xml',
        'sidoName': '전국',
        'numOfRows': '10000',  # 10000줄 데이터
        'ver': '1.3'
    }

    response = requests.get(SERVICE_URL, params=params)

    print(response.status_code)
    response.raise_for_status()  # 오류 발생 시 예외를 던짐

    xml_data = response.text
    df = parse_to_dataframe(xml_data)  # XML 데이터를 DataFrame으로 변환

    # BigQuery 클라이언트 설정
    client = bigquery.Client(project=PROJECT_ID)

    table_ref = f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}"

    job_config = bigquery.LoadJobConfig(
        write_disposition=bigquery.WriteDisposition.WRITE_APPEND,  # 데이터가 추가되도록 설정
        autodetect=True  # 자동으로 schema를 감지하도록 설정
    )

    # BigQuery에 데이터 업로드
    job = client.load_table_from_dataframe(df, table_ref, job_config=job_config)
    job.result()  # 완료될 때까지 기다림

    print(f"성공적으로 {len(df)}개의 레코드 BigQuery에 업로드 완료.")


with DAG(
    dag_id='air_mission18',
    schedule_interval='@hourly',
    start_date=days_ago(1),
    catchup=False,
    tags=['bigquery'],
) as dag:

    load_task = PythonOperator(
        task_id='load_air_quality_to_bq_18',
        python_callable=fetch_and_load_to_bq,
        provide_context=True
    )

    load_task